### ISSUE TITLE
UTF8MB4 charset for mysql

### ISSUE THREAD

**Issue by b-m-f** [wallabag/docker#111]
When installing with the `mysql` driver, the database charset should be set to `UTF8MB4`.

According to https://doc.wallabag.org/en/admin/parameters.html .

**Comment by shikasta-net** [comment]
Are you querying the default uft8 encoding in parameters.yml when launching wallabag-docker?  i had this issue too.  Eventually I found that the ansible entry point already has `SYMFONY__ENV__DATABASE_CHARSET` but it's not documented. 

Relatedly, can anyone confirm if the file _root/var/www/wallabag/app/config/parameters.yml_ in the repository is actually used anymore?  It took longer figure out the above because I was trying to find a way to edit a file that was being overwritten.
