### ISSUE TITLE
2.3.6 Docker build not available

### ISSUE THREAD

**Issue by mxjeff** [wallabag/docker#144]
how come docker image lags behing on hub.docker.com/r/wallabag/wallabag ?

**Comment by nsteinmetz** [comment]
cc @j0k3r @xsteadfastx

**Comment by j0k3r** [comment]
Docker images were created using GitHub Services which are now deprecated since January 31, 2019. That's why the 2.3.6 tag hasn't reached Docker Hub.

I manually created the 2.3.6 tag on Docker hub: https://hub.docker.com/r/wallabag/wallabag/tags
And the 2.3.7 should be created automatically next time.

**Comment by nsteinmetz** [comment]
thanks !

**Comment by mxjeff** [comment]
Thanks :smiley: !
