### ISSUE TITLE
How to access wallabag also from my VPN address and not only locally?

### ISSUE THREAD

**Issue by garret** [wallabag/docker#271]
I have setup wallabag to work locally (`SYMFONY__ENV__DOMAIN_NAME="http://192.168.0.10:8888"`). Thus, I connect to `http://192.168.0.10:8888` to access wallabag. However, I have also setup a wireguard VPN to access my server from outside. If wallabag would work like radarr or sonarr, I would just type `http://my-vpn-address:8888` and reach it also from outside but that seems not true as I only get the webpage with text but not pictures. 

Is there a way to mirror the local traffic also to my VPN address? Maybe do I have to modify the `nginx.conf`?

**Comment by jtagcat** [comment]
This issue is off-topic, and not related to wallabag nor wallabag docker support.

If you already use a reverse proxy, use it. Otherwise every computer on the internet by using `0.0.0.0:8888`. Assuming NAT, it should exclude access to IPv4 (but might not IPv6) devices outside your LAN.

No further support will be provided here. The issue can be closed. You may try for example https://forum.level1techs.com or https://linustechtips.com

**Comment by RrOoSsSsOo** [comment]
Check out the solution in this GitHub repository https://github.com/RrOoSsSsOo/docker-wallabag-proxy

**Comment by garret** [comment]
Solved thanks to @RrOoSsSsOo
