### ISSUE TITLE
No login possible with 2.6.1

### ISSUE THREAD

**Issue by Shadow27374** [wallabag/docker#343]
With the new version (2.6.1), I get the following message when logging in:

> Authentication request could not be processed due to a system problem

If I use the previous Docker image (2.5.4) it works.

**Comment by Shadow27374** [comment]
> @YouveGotMeowxy first you need to change the version number of the docker image you use, thus you can use the command below to update the database and it should be enough.
> 
> @Shadow27374 you should be able to do that by running the following steps:
> 
> ```
> docker-compose stop php
> docker-compose run --rm php migrate
> docker-compose up -d php
> ```

Did it now with the SQL statements. Next time I can test that too.

**Comment by Linuxine** [comment]
> > For information, I am currently using the Docker Image from https://hub.docker.com/r/wallabag/wallabag, with a sqlite database.
> 
> If I understand correctly you need the large block for sqlite:
...
> 
> But if it works for you now, it doesn't matter.

Okay I am so dumb :zany_face: 
I have misread the list of queries: actually it is the same as the one I have performed, but as in old version of sqlite there is no way to delete a column or change a column type, they copy the table as temporary tables without the column to drop or with a new name for the column to rename. So it WAS in the list of queries :sweat_smile: 

I will edit my comment to precise my commands only work with sqlite > 3.35.

**Comment by YouveGotMeowxy** [comment]
> @YouveGotMeowxy first you need to change the version number of the docker image you use, thus you can use the command below to update the database and it should be enough.
> 
> @Shadow27374 you should be able to do that by running the following steps:
> 
> ```
> docker-compose stop php
> docker-compose run --rm php migrate
> docker-compose up -d php
> ```

Sorry for being a noob here, but I'm still a bit confused.

I use this to pull the container: `wallabag/wallabag:latest`

And repulled the container so it's currently running the `latest` version. (And I can't seem to find a way to view it's version anywhere, even in the docs for a cline cmd) to verify the current version.

And then if I shell into the container there's no docker-compose command?

Just as a side note if it makes any difference, I'm using the Mysql db method rather than sqlite method.
