### ISSUE TITLE
Docker Environment Mailer Credentials?

### ISSUE THREAD

**Issue by gitwittidbit** [wallabag/docker#388]
So I set up Wallabag with docker compose some time ago und hadn't used it in a while. But the instance is still there.

Besides my admin account, I also set up a user account. But for some reason, it does not accept my user credentials for it anymore ("invalid credentials"). The admin account still accepts my credentials but there is no way to reset the password for a user.

I can click on"Forgot your password" for the user account on the login page but then I get an error that wallabag could not connect to some stream on 127.0.0.1:465. Which is no surprise, I guess.

The surprise is that I set an environment variable (SYMFONY__ENV__MAILER_HOST) in my docker compose to point to the mail server on some other host. But it seems that the variable is no longer in use. Instead there is a new variable (SYMFONY__ENV__MAILER_DSN) that I can use. But the docs don't mention the environment variables for mailer user and mailer password anymore. So how do I tell Wallabag the account credentials???

Moreover, I just tried to keep the old environment variables (SYMFONY__ENV__MAILER_USER, SYMFONY__ENV__MAILER_PASSWORD) but that doesn't work either. It tells me that it could not establish a connection with my mailer host because it can't resolve the mailer host's FQDN.

If I change /etc/resolv.conf to my network's nameserver, it seems to be able to resolve the mailer host's FQDN but then I get an error that it can't resolve the DB host... 

So I'm really stuck at this point.

How do I enable sending password reset links (or anything else probably)?

Thanks!

**Comment by j0k3r** [comment]
> But the docs don't mention the environment variables for mailer user and mailer password anymore. So how do I tell Wallabag the account credentials???

Maybe you were looking at the wrong place? It's here: https://doc.wallabag.org/en/admin/mailer

**Comment by Kdecherf** [comment]
I don't think the name resolution issue you're describing here is related to wallabag. You may need to check your Docker setup

**Comment by sundogak** [comment]
@gitwittidbit The issue here is as you noted is that from version 2.5 onward the old mailer environment variables were [deprecated ](https://doc.wallabag.org/en/admin/upgrade#upgrading-from-25x-to-26x)and no longer work. You will get a server 500 error.  After some fiddling here is a string that works with Gmail SMTP:

`SYMFONY__ENV__MAILER_DSN: gmail+smtp://insertyourname@gmail.com:apppassword@default`

The above replaces all the separate environmental variables for Mailer.  I initially tried using my Outlook SMTP and the issue there is that Wallabag has hardcoded a "send as" email (noreply@wallabag.org) and Outlook expects it to match your username (i.e., Outlook email) so it will fail sending.  

The clue on how to use the Gmail command came from the Symfony site link [here](https://symfony.com/doc/current/mailer.html#overriding-default-smtp-authenticators).  Other providers are listed beyond Gmail.  

The Docker ENV instructions should be updated to indicate that as anything using the older Mailer variables will not work moving forward and the new ENV variable is: SYMFONY__ENV__MAILER_DSN:

**Comment by sundogak** [comment]
This works for versions 2.5 and newer for me in Docker Wallabag: 
`SYMFONY__ENV__MAILER_DSN: gmail+smtp://insertyourname@gmail.com:apppassword@default`

Note that I couldn't get Outlook SMTP to work as Outlook expects the reply address to be same as user name and it seems based on return error code that Wallabag is sending "noreply@wallabag.org" as sender when tried this string:
`SYMFONY__ENV__MAILER_DSN: smtp://insertyouremail@outlook.com:apppassword@smtp-mail.outlook.com:587`
